version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: liverpool_sql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: liverpool_db
      MYSQL_USER: liverpooluser
      MYSQL_PASSWORD: liverpoolpassword
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
      - ./config/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m
      timeout: 8s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: adminer-lab
    depends_on:
      - mysql
    ports:
      - "8081:8080"

volumes:
  mysql_data:
