name: Docker Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: liverpool_db
          MYSQL_USER: liverpool_db
          MYSQL_PASSWORD: liverpoolpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=30s --health-retries=3 --health-timeout=5s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker-compose build

      - name: Run Docker Containers
        run: docker-compose up -d

      - name: Wait for MySQL to be ready
        run: |
          sleep 20
          docker exec liverpool_db mysqladmin ping -h localhost --user=root --password=rootpassword

      - name: Run tests (replace with your actual test command)
        run: |
          # Replace this with your actual test command, e.g., running a test script
          echo "Running tests"

      - name: Tear down containers
        run: docker-compose down
